# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: '#welcome'
    weight: 9
  - name: 简介
    url: '#about'
    weight: 10
  - name: 成员
    url: '#people'
    weight: 15
  - name: 新闻
    url: '#post'
    weight: 20
  - name: 项目
    url: '#projects'
    weight: 12
  - name: 论文
    url: '#publications'
    weight: 11


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
